[project]
authors = ["Ryan Oates <ryanfullstack@icloud.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
description = "Add a short description here"
name = "digital-logic"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
